name: CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    
    steps:
      - uses: actions/checkout@v2

      - name: Login Clever Cloud
        run: clever login --token ${{CLEVER_TOKEN}} --secret ${{CLEVER_SECRET}}

      - name: Build Dockerfile
        run: |
          git fetch --prune --unshallow
          clever deploy -a node-app-docker-test
